apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  selector:
    matchLabels:
      run: jenkins-demo
  replicas: 1
  template:
    metadata:
      labels:
        run: jenkins-demo
    spec:
      containers:
      - name: jenkins-demo
        image: 973141472776.dkr.ecr.ap-south-1.amazonaws.com/tekton/jenkins-demo3:v3.4
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo
  labels:
    run: jenkins-demo
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  type: ClusterIP
  selector:
    run: jenkins-demo
