apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  selector:
    matchLabels:
      run: jenkins-demo
  replicas: 1
  template:
    metadata:
      labels:
        run: jenkins-demo
    spec:
      containers:
      - name: jenkins-demo
        image: add503e3a47ee468bb54cfd9b6e231b7-29dbf7660ec56ab8.elb.ap-south-1.amazonaws.com/tekton/jenkins-demo3:v2.2
        ports:
        - containerPort: 9080
